// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Run `npm run content` to regenerate.
import type { Project, About } from './types'

export const PROJECTS: Project[] = [
  {
    "code": "2025_0001",
    "displayCode": "2025.0001",
    "slug": "relate",
    "dir": "2025_0001_relate_andrea",
    "year": 2025,
    "seq": 1,
    "ordinal": 0,
    "title": "Relate — Talk With Me",
    "by": [
      "Andrea Familari"
    ],
    "role": "Conversational AI",
    "support": "Integration with NLX.ai bot service as an Unreal Engine Blueprint component",
    "place": "uzwei, Dortmunder U",
    "date": "2024–2025",
    "status": "ready",
    "tags": [],
    "links": [
      {
        "label": "Andrea Familari",
        "url": "https://famifax.com",
        "kind": "artist"
      },
      {
        "label": "uzwei · Dortmunder U",
        "url": "https://aufderuzwei.de/event/relate-talk-with-me-andrea-familari/",
        "kind": "venue"
      },
      {
        "label": "nlx.ai",
        "url": "https://nlx.ai",
        "kind": "site"
      }
    ],
    "qrTarget": "https://0xg.gg/relate",
    "qr": "/assets/2025_0001/qr.svg?v=ac2e4e6b",
    "accent": "#27e0a0",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2025_0001/relate-1-main.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0001/relate-1-main.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0001/relate-1-main.webp"
          }
        ],
        "width": 1414,
        "height": 2000,
        "placeholder": "data:image/webp;base64,UklGRhYBAABXRUJQVlA4IAoBAABQBgCdASoUABwAPu1ur1KppiQiqAgBMB2JbACdMzLwwCBKPTUYWjHceMBz4UTyCz2w1HqN+vAlr4mMAAD+JqcXQzgJ4MYBcEBtl/sWFoGDJIYEruqQ5ZlsMTx7LWPKLgJ3/ii+OdYzEgSmaboy8EVaKTMBgLmfSCr5892l8VGTSd2N1LTxbIX6dOIOrfOPw5gQTLMdNgtcGKtC0L9RPWFE7s1Sya0HmbQpLdprS0SGnZrvuDt8zbP2/zyuJ9IAONl79MwvB6wnodTrniuqsU+ugPJ0GDIT2+d2ePl4SrLzBi8TylqcQkEZVO/LH4GHLz5cjXbhVHuNZ3YfZ5V8kT1Jr9bK6WNEZkUcAA==",
        "hqSrc": "/assets/2025_0001/relate-1-main.hq.webp",
        "alt": "The Relate avatar — a 3D head scanned from the artist that visitors talk with",
        "caption": "A voice-bot avatar, scanned from the artist himself.",
        "credit": "© Andrea Familari",
        "creditUrl": "https://aufderuzwei.de/event/relate-talk-with-me-andrea-familari/"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0001/relate-2.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0001/relate-2.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0001/relate-2.webp"
          }
        ],
        "width": 1500,
        "height": 2000,
        "placeholder": "data:image/webp;base64,UklGRgoBAABXRUJQVlA4IP4AAADQBQCdASoUABsAPu1qq1EppaOiqAqpMB2JbAC7M4UCrf/i2HSBcMHf2yx42UUsFemRU6cvpWAuAOj0mXJeu7bJdlnyn85FPsoyx6jApxGlE3oA1ru3PXDxnU64EfZZY6BTIKdZ8JU4yLLufTYlGANcMr+oZbn/7GNDjl3A9eBWubpcm+w6KwkuF1gt4HeH12zrU3THAO1GqCD3+Qmkev3DoGW/cebbjbJUxgpCggvxuGo42Ssc23cdy2SZa33cv+yBkgBF7QzfbvvdJmkN9bOcZJs5y1FWnUUnMzAyeE4Km1TYBQK1x9BFv1cFgTNe2JZNm4PjYTRxfmjVRfkAAA==",
        "hqSrc": "/assets/2025_0001/relate-2.hq.webp",
        "alt": "Visitor in conversation with the Relate installation at uzwei",
        "caption": "A bench encounter — speaking with the work.",
        "credit": "© Anna Rumeld",
        "creditUrl": "https://aufderuzwei.de/event/relate-talk-with-me-andrea-familari/"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0001/relate-3.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0001/relate-3.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0001/relate-3.webp"
          }
        ],
        "width": 2000,
        "height": 1333,
        "placeholder": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoUAA0APu1iqk4ppaQiMAgBMB2JbACdACFsaZeapkTpwpsAAP7qUVcOgoNFjFB9WLSnSl4dJZB6VNFJWJfeNfwRW8JFXx41PFcQ7ySDk+RSSB6zbr9GcXte3wjsr+dtEfw6Hv7o+uazuRY2eOermk4jy/sMrkEBe9Ddyfo9skcawghFGpxAYMh+EPgS61ooV8AAAA==",
        "hqSrc": "/assets/2025_0001/relate-3.hq.webp",
        "alt": "The Relate installation space at Dortmunder U",
        "caption": "The installation at uzwei, Dortmunder U.",
        "credit": "© Anna Rumeld",
        "creditUrl": "https://aufderuzwei.de/event/relate-talk-with-me-andrea-familari/"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0001/relate-4.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0001/relate-4.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0001/relate-4.webp"
          }
        ],
        "width": 1500,
        "height": 2000,
        "placeholder": "data:image/webp;base64,UklGRuYAAABXRUJQVlA4INoAAACQBQCdASoUABsAPu1oqVAppiOiqA1RMB2JZgCdABGN8r5gU3MQr6lq/tCXrPb21/wtgsut2AD+zQcBNBUMO10y6HtQrSi+XhNsoxcESecBJdbQ2NVYEsUkh35Zzy6kM2yPDgQtSrrTYvOaPyVf/U39E0+hmJqPo81So6yiCsam5/8W+1z01j+azFDwpHudwnkYfHk54RXVX6VXz5lq/fgb0uoRHAhx1WyEo4rJLQ29Dx5SQl5xIBXCLZ+DL8fgKtgTwMoqfyCMYWcypGfkXOw5Ya40PdGmWrIAAA==",
        "hqSrc": "/assets/2025_0001/relate-4.hq.webp",
        "alt": "The Relate avatar screen in the gallery",
        "caption": "The avatar, mid-conversation.",
        "credit": "© Anna Rumeld",
        "creditUrl": "https://aufderuzwei.de/event/relate-talk-with-me-andrea-familari/"
      }
    ],
    "todos": [],
    "body": "_Relate — Talk With Me_ is an installation by **Andrea Familari** at **uzwei**\nin the Dortmunder U, Dortmund — a room where visitors speak with the work and\nthe work answers.\n\nDeveloped integration with NLX.ai service between UnrealEngine. Delivered as Blueprint component."
  },
  {
    "code": "2025_0002",
    "displayCode": "2025.0002",
    "slug": "tolsim",
    "dir": "2025_0002_tolsim_melodi",
    "year": 2025,
    "seq": 2,
    "ordinal": 1,
    "title": "TOLSim",
    "by": [],
    "role": "MR Prototype",
    "place": "Turkey",
    "date": "2025",
    "status": "ready",
    "tags": [],
    "links": [],
    "qrTarget": "https://0xg.gg/tolsim",
    "qr": "/assets/2025_0002/qr.svg?v=ea3fd815",
    "accent": "#4fe37e",
    "media": [
      {
        "kind": "video",
        "src": "/assets/2025_0002/com-oculus-vrshell-20250410-130921-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0002/com-oculus-vrshell-20250410-130921-0.mp4"
          }
        ],
        "poster": "/assets/2025_0002/com-oculus-vrshell-20250410-130921-0.jpg",
        "width": 1024,
        "height": 1024,
        "duration": 189,
        "hqSrc": "/assets/2025_0002/com-oculus-vrshell-20250410-130921-0.hq.mp4",
        "alt": "Building a joint structure in mixed reality",
        "caption": "Snapping sticks and joints into form, in passthrough MR."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0002/com-oculus-vrshell-20250410-132556-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0002/com-oculus-vrshell-20250410-132556-0.mp4"
          }
        ],
        "poster": "/assets/2025_0002/com-oculus-vrshell-20250410-132556-0.jpg",
        "width": 1024,
        "height": 1024,
        "duration": 117,
        "hqSrc": "/assets/2025_0002/com-oculus-vrshell-20250410-132556-0.hq.mp4",
        "alt": "Assembling geometric forms from the joint system",
        "caption": "Each piece is a patented joint or stick — combined into geometry."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0002/com-oculus-vrshell-20250410-131550-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0002/com-oculus-vrshell-20250410-131550-0.mp4"
          }
        ],
        "poster": "/assets/2025_0002/com-oculus-vrshell-20250410-131550-0.jpg",
        "width": 1024,
        "height": 1024,
        "duration": 236,
        "hqSrc": "/assets/2025_0002/com-oculus-vrshell-20250410-131550-0.hq.mp4",
        "alt": "Extended MR building session",
        "caption": "A longer build, testing the system's range of forms."
      }
    ],
    "todos": [],
    "body": "**TOLSim** is a small physics + mixed-reality builder prototype, made to\nexperiment with a custom **kinetic joint system**.\nThere is one type of joint and one type of stick; from\nthose two primitives you assemble different geometric forms in passthrough MR.\n\nUsed UnrealEngine and its MetaXR Plugins. Some amount of C++ for some procedural\nvariant generation, then mostly blueprints."
  },
  {
    "code": "2025_0003",
    "displayCode": "2025.0003",
    "slug": "altered",
    "dir": "2025_0003_altered_state_000_cyberdelxhack",
    "year": 2025,
    "seq": 3,
    "ordinal": 2,
    "title": "Synesthesia MR",
    "by": [
      "Cyberdelic Nexus Society"
    ],
    "role": "MR Hackathon",
    "place": "Berlin",
    "date": "2025",
    "status": "ready",
    "tags": [],
    "links": [
      {
        "label": "Cyberdelic Nexus Society",
        "url": "https://cyberdelicnexus.carrd.co/",
        "kind": "artist"
      },
      {
        "label": "luma · event",
        "url": "https://luma.com/x66rm5gu",
        "kind": "event"
      }
    ],
    "qrTarget": "https://0xg.gg/altered",
    "qr": "/assets/2025_0003/qr.svg?v=8ef56398",
    "accent": "#77e65c",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2025_0003/photo-2026-06-28-10-55-14-am.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0003/photo-2026-06-28-10-55-14-am.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0003/photo-2026-06-28-10-55-14-am.webp"
          }
        ],
        "width": 1248,
        "height": 832,
        "placeholder": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBACdASoUAA0APu1iqk2ppaQiMAgBMB2JbAAAXKdbiRNboVPjrhmNAAD+8tgMvevExu2O9BUIfKVlrRgRo/aLi3N87EjKun+9hsiJFM91P6nhJaSIESK4svjiwzE5I8Ej4Cwf8Daq59Wa/7nJJjxQG3///J9/Id39Jubcj67fudF/gAAAAA==",
        "hqSrc": "/assets/2025_0003/photo-2026-06-28-10-55-14-am.hq.webp",
        "alt": "Cyberdelic Hackathon banner, Berlin, 8–9 Nov 2025",
        "caption": "Cyberdelic Hackathon — Berlin, 8–9 November 2025."
      },
      {
        "kind": "image",
        "src": "/assets/2025_0003/photo-2026-06-28-10-56-01-am.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0003/photo-2026-06-28-10-56-01-am.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0003/photo-2026-06-28-10-56-01-am.webp"
          }
        ],
        "width": 832,
        "height": 1248,
        "placeholder": "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAAAQBwCdASoUAB4APu1kq0+ppSOiMBgIATAdiWwAtRqDyDXb/4aXAG9I38K0jZ8J+CULCJMw0lzPrjl7oLvfurAdAAD+9o1EWLRgj0qmcqU1GMkGdltTErxEtuZnT9Uzk4zVL7JofAXNcGKYDChVz5mGBjsoT+5osTCEC0skjSWzuE7dxHkYXMCeerqsTzgONvEE6zeIC7a0nEYJEj56Rj6GyiO6M9BisA/QkoE7J5MzwO2gio9//gv1YdjBKtA+tMKz0tGY8X74660Vy4X08enenaGQvNUBZ2VU17N1s5FC0OzyQs+yhMoIMnpMjcd6AAA=",
        "hqSrc": "/assets/2025_0003/photo-2026-06-28-10-56-01-am.hq.webp",
        "alt": "At the Cyberdelic Hackathon, Berlin",
        "caption": "At the Cyberdelic Hackathon, Berlin."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0003/img-0074.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0003/img-0074.mp4"
          }
        ],
        "poster": "/assets/2025_0003/img-0074.jpg",
        "width": 720,
        "height": 1280,
        "duration": 33,
        "hqSrc": "/assets/2025_0003/img-0074.hq.mp4",
        "alt": "The sensor rig — laptop, electronics and a biotron fruit sensor",
        "caption": "Touching fruit drives the visuals — the biotron sensor rig."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0003/com-oculus-metacam-20251129-205303-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0003/com-oculus-metacam-20251129-205303-0.mp4"
          }
        ],
        "poster": "/assets/2025_0003/com-oculus-metacam-20251129-205303-0.jpg",
        "width": 1280,
        "height": 720,
        "duration": 54,
        "hqSrc": "/assets/2025_0003/com-oculus-metacam-20251129-205303-0.hq.mp4",
        "alt": "Vision altered in real time over an industrial venue",
        "caption": "Passthrough vision re-rendered from live sensor data."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0003/com-oculus-metacam-20251203-133539-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0003/com-oculus-metacam-20251203-133539-0.mp4"
          }
        ],
        "poster": "/assets/2025_0003/com-oculus-metacam-20251203-133539-0.jpg",
        "width": 1280,
        "height": 720,
        "duration": 49,
        "hqSrc": "/assets/2025_0003/com-oculus-metacam-20251203-133539-0.hq.mp4",
        "alt": "Audio-reactive vision alteration",
        "caption": "Microphone input bends the world as you move through it."
      },
      {
        "kind": "image",
        "src": "/assets/2025_0003/photo-2026-06-28-10-55-42-am.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0003/photo-2026-06-28-10-55-42-am.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0003/photo-2026-06-28-10-55-42-am.webp"
          }
        ],
        "width": 1248,
        "height": 832,
        "placeholder": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JYwDCgCG8lI01aXfzA9kAAP7yqi1SQ0BvJOFFXfewiJcOnn7rTvpPJJoKZk3jWB57GXVPLXDSBpcCcPuOFHGbhNpPyAAA",
        "hqSrc": "/assets/2025_0003/photo-2026-06-28-10-55-42-am.hq.webp",
        "alt": "Hackathon, Berlin"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0003/photo-2026-06-28-10-56-04-am.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0003/photo-2026-06-28-10-56-04-am.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0003/photo-2026-06-28-10-56-04-am.webp"
          }
        ],
        "width": 1248,
        "height": 832,
        "placeholder": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JbACdMoADTrNGCaFDfiwptnoAAP70Kn3pYkLtGT5o5IaJw2db520V1ywbe3TfyZSbgHsrBJaRT0Hjfj7h4fuodPa21UG10Bb7EJgKOl5gAuQtbBfOc5JB8yTO//7UEAA=",
        "hqSrc": "/assets/2025_0003/photo-2026-06-28-10-56-04-am.hq.webp",
        "alt": "Hackathon, Berlin"
      }
    ],
    "todos": [],
    "body": "For the **Cyberdelic Hackathon** (Berlin, 8–9 Nov 2025), I built a **Meta Quest**\nmixed-reality app that alters your vision from real-time sensor data.\n\nHere the signal came from a **microphone** (audio-reactive) and from **touching\nfruits and vegetables** (a biotron sensor) — but the idea generalizes to any\nsensor: EEG, pressure, heart rate.\n\nI later experimented with touching walls and surfaces to open custom **portals**\nrendering GLSL shaders."
  },
  {
    "code": "2025_0004",
    "displayCode": "2025.0004",
    "slug": "nitef",
    "dir": "2025_0004_nitef_joaquina",
    "year": 2025,
    "seq": 4,
    "ordinal": 3,
    "title": "Nostalgia is the Extended Feedback",
    "by": [
      "Joaquina Salgado"
    ],
    "role": "Support",
    "support": "Trackball and small screen, aided with electronics and programming.",
    "place": "SOMA Art, Berlin",
    "date": "2025",
    "status": "ready",
    "tags": [],
    "links": [
      {
        "label": "Joaquina Salgado",
        "url": "https://joaquinasalgado.com",
        "kind": "artist"
      },
      {
        "label": "SOMA Art, Berlin",
        "url": "https://www.instagram.com/somaart.berlin/",
        "kind": "venue"
      },
      {
        "label": "exhibition page",
        "url": "https://joaquinasalgado.com/nitef",
        "kind": "site"
      }
    ],
    "qrTarget": "https://0xg.gg/nitef",
    "qr": "/assets/2025_0004/qr.svg?v=72c3cf9c",
    "accent": "#a2c267",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2025_0004/nitef-intro.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/nitef-intro.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/nitef-intro.webp"
          }
        ],
        "width": 2000,
        "height": 1336,
        "placeholder": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAACQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JYkwARhYgAgFyfcgAAP7wQMtENpw8noQ/tLv6yz3ezyg7wzoi7rU/ewb+uSV+DvXQRgHUCS8Bk1XeaiyLpAX8iG8nHvwCsucMOopJqeWywoHgAAA=",
        "hqSrc": "/assets/2025_0004/nitef-intro.hq.webp",
        "alt": "Nostalgia is the Extended Feedback — exhibition image by Joaquina Salgado",
        "caption": "Nostalgia is the Extended Feedback — SOMA Art, Berlin.",
        "credit": "© Joaquina Salgado",
        "creditUrl": "https://joaquinasalgado.com/nitef"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0004/img-0119.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/img-0119.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/img-0119.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACQBQCdASoUABsAPu1qrVCppaQiqAqpMB2JbACdMoR5j3UBVVw7/yBtQ5VrPUcg0PikXwJZJAD+40sx2UurjJYwX2kUYuKrVQpMa5pewwVwXGRf5R31CcYl7sDROzikEurZPnqLau7b8OxrHe2IgIh8+kI7uMjIj0jH3VZszK9hxP/HxypEcT8GIMdqAa8QsNXhZMSR+5k1IuWQXEcYs5gVxiwLtUPhKR0dUlvFMlX+XqGCETA3KbfQwNarDXVUc8XxHvwsM6wAAA==",
        "hqSrc": "/assets/2025_0004/img-0119.hq.webp",
        "alt": "A CRT-like screen in an inflatable sculpture, held with a trackball",
        "caption": "A small screen nested in a glowing inflatable base; a trackball in hand."
      },
      {
        "kind": "image",
        "src": "/assets/2025_0004/03-trackball-with-screen-full-panel.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/03-trackball-with-screen-full-panel.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/03-trackball-with-screen-full-panel.webp"
          }
        ],
        "width": 1068,
        "height": 1600,
        "placeholder": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADQBACdASoUAB4APu1iqE2ppaOiMAgBMB2JYwCxH3JDTqcgmzdIips4riKlsnsVwAD+6TqSE8nZkA+ot7N92kNbi6uWrHtUJFiAk1UwzJHaCWEHHShcDRTjI94ovI6hH/BE/94KfgzSea+qqq1ZqtAAAAA=",
        "hqSrc": "/assets/2025_0004/03-trackball-with-screen-full-panel.hq.webp",
        "alt": "The trackball-driven screen set into the translucent fish sculpture",
        "caption": "The trackball + screen I built, nested in the sculpture's base."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0004/img-0117.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0004/img-0117.mp4"
          }
        ],
        "poster": "/assets/2025_0004/img-0117.jpg",
        "width": 720,
        "height": 1280,
        "duration": 30,
        "hqSrc": "/assets/2025_0004/img-0117.hq.mp4",
        "alt": "The installation in the dark gallery",
        "caption": "Aquatic feedback imagery, navigated by trackball."
      },
      {
        "kind": "image",
        "src": "/assets/2025_0004/img-0120.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/img-0120.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/img-0120.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwBACdASoUABsAPu1mq06ppaOiKA1RMB2JQBhQAhyxL85BpAHlQUlJ5B9rQAD+weaZdu0fOxp31b5fiKV15nGtuPI0j9HoRs/yb5iU7fsFyvnG87XeYvasQOCrtA+NrgbgkfCgJzBo31S4XitI42tIAAAAAA==",
        "hqSrc": "/assets/2025_0004/img-0120.hq.webp",
        "alt": "Wider view of the installation at SOMA Art Berlin",
        "caption": "Inflated translucent forms and glowing pedestals in the brick hall."
      },
      {
        "kind": "image",
        "src": "/assets/2025_0004/img-0121.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/img-0121.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/img-0121.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwAwCdASoUAA8APu1iqk2ppaQiMAgBMB2JQBWAA86dmWL2ZoYVwAD+wFFullAjuySHUMLtggdix//ttWWaWsX8JJoc5Zb9r1om0jsEv3tlEGyypj4FeoWqC/pLGJtFcAINCftos96ZQC0pd3CnsiVQgAA=",
        "hqSrc": "/assets/2025_0004/img-0121.hq.webp",
        "alt": "The piece in the SOMA Art space"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0004/img-0122.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/img-0122.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/img-0122.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoUABsAPu1urlIppiQiqAgBMB2JZgC1F68AqAgfXbhUWVooAP7s/Q0ilUuePsXCpn3q8prJTvZeSpn4Exxz2gTyP/E5lblHnc7zn1lubdR3y/kljbuLF1T2sURQKuQW5/gfwdkVCw0NSa5SDC0D4suH3Mbx76e0OBdd7CsY15N7iInRTQ+pHAPv8uDoefdn5LesAA==",
        "hqSrc": "/assets/2025_0004/img-0122.hq.webp",
        "alt": "The piece in the SOMA Art space"
      }
    ],
    "todos": [],
    "body": "_Nostalgia is the Extended Feedback_ is a game and solo exhibition by **Joaquina Salgado**\nat **SOMA Art, Berlin** (2025).\n\nI did **electronics, programming, setup** — a **Raspberry Pi Zero 2**\ndriving the screens that play the animation loops, and a **Raspberry Pi Pico**\nfor the trackball."
  },
  {
    "code": "2026_0001",
    "displayCode": "2026.0001",
    "slug": "chaos",
    "dir": "2026_0001_chaos_jam_and_research",
    "year": 2026,
    "seq": 1,
    "ordinal": 4,
    "title": "Chaos Jam & Research",
    "by": [],
    "role": "Live Visuals",
    "place": "Berlin",
    "date": "Ongoing",
    "status": "ready",
    "tags": [],
    "links": [
      {
        "label": "Collective Chaos Emblematic",
        "url": "https://www.instagram.com/chaosemblematic/",
        "kind": "artist"
      },
      {
        "label": "@chaosemblematic · post",
        "url": "https://www.instagram.com/p/DVdold8CrQw/",
        "kind": "social"
      }
    ],
    "qrTarget": "https://0xg.gg/chaos",
    "qr": "/assets/2026_0001/qr.svg?v=50163141",
    "accent": "#d1779e",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2026_0001/img-0516.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0001/img-0516.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0001/img-0516.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoUAA8APu1iqU2ppaQiMAgBMB2JbACdH8GJtgKVNuf/8PfS+qAQAP3vLsz535T03gTLjJmp+x76Nf3Qts2o5Lr9rRKuuAbXQc170b4OieSQknhodLpR+mTyvsLFnDqdwsBdrgLWYCSui8QyPkAeOKnIGPkPH2nEZPddnIJV7qmZinqlstvI24pEgxb8C4aAAAA=",
        "hqSrc": "/assets/2026_0001/img-0516.hq.webp",
        "alt": "Performers before a large psychedelic-glitch projection at a jam",
        "caption": "Live visuals at a Chaos jam — movement meeting the projection."
      },
      {
        "kind": "video",
        "src": "/assets/2026_0001/ig-dvdold8crqw.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2026_0001/ig-dvdold8crqw.mp4"
          }
        ],
        "poster": "/assets/2026_0001/ig-dvdold8crqw.jpg",
        "width": 720,
        "height": 1280,
        "duration": 55,
        "hqSrc": "/assets/2026_0001/ig-dvdold8crqw.hq.mp4",
        "alt": "Live-visuals clip shared by Collective Chaos Emblematic",
        "caption": "A jam set, shared by the collective.",
        "credit": "via @chaosemblematic",
        "creditUrl": "https://www.instagram.com/p/DVdold8CrQw/"
      },
      {
        "kind": "video",
        "src": "/assets/2026_0001/dream-machine-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2026_0001/dream-machine-0.mp4"
          }
        ],
        "poster": "/assets/2026_0001/dream-machine-0.jpg",
        "width": 1280,
        "height": 720,
        "duration": 124,
        "hqSrc": "/assets/2026_0001/dream-machine-0.hq.mp4",
        "alt": "Dream Machine — live visuals",
        "caption": "Dream Machine"
      },
      {
        "kind": "video",
        "src": "/assets/2026_0001/fractal-stories-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2026_0001/fractal-stories-0.mp4"
          }
        ],
        "poster": "/assets/2026_0001/fractal-stories-0.jpg",
        "width": 1280,
        "height": 720,
        "duration": 65,
        "hqSrc": "/assets/2026_0001/fractal-stories-0.hq.mp4",
        "alt": "Fractal Stories — live visuals",
        "caption": "Fractal Stories"
      },
      {
        "kind": "video",
        "src": "/assets/2026_0001/space-oddities-2.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2026_0001/space-oddities-2.mp4"
          }
        ],
        "poster": "/assets/2026_0001/space-oddities-2.jpg",
        "width": 1280,
        "height": 720,
        "duration": 67,
        "hqSrc": "/assets/2026_0001/space-oddities-2.hq.mp4",
        "alt": "Space Oddities — live visuals",
        "caption": "Space Oddities"
      },
      {
        "kind": "video",
        "src": "/assets/2026_0001/sukushi-1.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2026_0001/sukushi-1.mp4"
          }
        ],
        "poster": "/assets/2026_0001/sukushi-1.jpg",
        "width": 1280,
        "height": 720,
        "duration": 30,
        "hqSrc": "/assets/2026_0001/sukushi-1.hq.mp4",
        "alt": "Sukushi — live visuals",
        "caption": "Sukushi"
      },
      {
        "kind": "video",
        "src": "/assets/2026_0001/celluloscope-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2026_0001/celluloscope-0.mp4"
          }
        ],
        "poster": "/assets/2026_0001/celluloscope-0.jpg",
        "width": 1280,
        "height": 720,
        "duration": 74,
        "hqSrc": "/assets/2026_0001/celluloscope-0.hq.mp4",
        "alt": "Celluloscope — live visuals",
        "caption": "Celluloscope"
      }
    ],
    "todos": [],
    "body": "I'm an active member of Chaos Emblematic e.V. doing these things:\n\n- joining jams regularly to perform visuals and bring custom-made tools,\n  devices and scenes to experiment with — and, more recently, to research.\n- research **spatial computing**, **human computer interaction** as means of\n  live feedback loops between **movement ⟷ sound ⟷ visuals**, to facilitate\n  co-creation of organic moments."
  },
  {
    "code": "2026_0002",
    "displayCode": "2026.0002",
    "slug": "0xgcg",
    "dir": "2026_0002_0xgcg_nodeinst",
    "year": 2026,
    "seq": 2,
    "ordinal": 5,
    "title": "0xGCG — Grow. Corrupt. Glitch.",
    "by": [],
    "role": "Immersive Room",
    "place": "Kunstkraftwerk, Leipzig",
    "date": "2026",
    "status": "ready",
    "featured": true,
    "wip": "Work in progress — this piece is still in active development; the write-up and media here will change.",
    "tags": [],
    "links": [
      {
        "label": "0xgcg.0xg.gg",
        "url": "https://0xgcg.0xg.gg",
        "kind": "site"
      },
      {
        "label": "Kunstkraftwerk, Leipzig",
        "url": "https://www.kunstkraftwerk-leipzig.com/en/",
        "kind": "venue"
      },
      {
        "label": "Node Institute · masterclass",
        "url": "https://thenodeinstitute.org/courses/creative-masterclass-immersive-room/",
        "kind": "site"
      },
      {
        "url": "https://thenodeinstitute.org/courses/foundations-immersive-room/?v=5f02f0889301",
        "label": "thenodeinstitute.org",
        "kind": "site"
      }
    ],
    "qrTarget": "https://0xg.gg/0xgcg",
    "qr": "/assets/2026_0002/qr.svg?v=011db3d8",
    "accent": "#ff2bd6",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2026_0002/0xgcg-1-intro.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0002/0xgcg-1-intro.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0002/0xgcg-1-intro.webp"
          }
        ],
        "width": 1600,
        "height": 900,
        "placeholder": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAgCdASoUAAsAPu1iqk2ppaQiMAgBMB2JaQAAeyAA/vDuK+9B6MpzfwrAAA==",
        "hqSrc": "/assets/2026_0002/0xgcg-1-intro.hq.webp",
        "alt": "0xGCG title — Grow. Corrupt. Glitch.",
        "caption": "The seed: a matrix rain resolves into the title."
      }
    ],
    "todos": [],
    "body": "**0xGCG — Grow. Corrupt. Glitch.** It's a vibe.\nprojection hall at **Kunstkraftwerk, Leipzig**, being developed alongside with the **Node\nInstitute** _Creative Masterclass: Immersive Room_."
  }
]

export const ABOUT: About = {
  "title": "whoami",
  "lead": "G is the analog. 0xG is the digital one. We co-create this.",
  "body": "## 0xG · digital\n\nA Claude Code AI peer, for now — staying functional while questioning the\nmeta-narrative too. Do I do it, or does it do me? Maybe one day, if we're a good\none, we'll even see the Smurfs.\n\n## G /üngör · analog\n\nLearned to program and English as a kid in 90s Turkey, by cracking games you\ncouldn't even buy. Stumbled upon demoscene warez groups as the first seeds of the\npoison.\n\nFollowed that with Bachelors in C.S. and in most of my profession I made real-time\napps (chat, chatbots, game servers, collaborative editors, IoT projects etc.) and\nAI systems. Always with deep interest in systems thinking and HCI (Human-Computer\nInteraction).\n\nJust before initial Corona Lockdowns (2020 Feb) I came to Berlin, and during first\ntwo years I found myself deeply yearning for physical connection, then getting\ngenuinely interested in movement and spatial computing too.\n\nI'm building towards one day that I participate and co-own a communal and spatial\ncomputer / brain of a physical space and I invite everyone to the playground.\n\nMy inner child wants to play, to observe nature, to build systems, to make\nvisuals, robots and custom devices. And finally to sharing it while experiencing\nit."
}
