// AUTO-GENERATED by scripts/build-content.mjs — do not edit by hand.
// Run `npm run content` to regenerate.
import type { Project } from './types'

export const PROJECTS: Project[] = [
  {
    "code": "2025_0001",
    "displayCode": "2025.0001",
    "slug": "relate",
    "dir": "2025_0001_relate_andrea",
    "year": 2025,
    "seq": 1,
    "ordinal": 0,
    "title": "Relate — Talk With Me",
    "subtitle": "Conversational-AI installation",
    "by": [
      "Andrea Familari"
    ],
    "role": "Conversational AI · Unreal Engine",
    "support": "Integration with NLX.ai bot service as an Unreal Engine Blueprint component",
    "place": "uzwei, Dortmunder U · Dortmund",
    "date": "2025",
    "status": "ready",
    "tags": [
      "Unreal Engine",
      "Conversational AI",
      "Installation"
    ],
    "links": [
      {
        "label": "nlx.ai",
        "url": "https://nlx.ai",
        "kind": "site"
      }
    ],
    "qrTarget": "https://0xg.gg/#relate",
    "qr": "/assets/2025_0001/qr.svg",
    "accent": "#27e0a0",
    "media": [],
    "todos": [
      "Fetch the information from website: . save it as md and also assets relative.",
      "Explain the project, that installation and my involvement",
      "No media yet — add files to imports/ (no-media card variant in use)."
    ],
    "body": "*Relate — Talk With Me* is an installation by **Andrea Familari** at **uzwei**\nin the Dortmunder U, Dortmund — a room where visitors speak with the work and\nthe work answers.\n\nI built the voice: an **NLX.ai** conversational agent wired into **Unreal Engine**\nas a reusable Blueprint component, so the runtime could listen, route intent and\nrespond in real time inside the engine driving the piece."
  },
  {
    "code": "2025_0002",
    "displayCode": "2025.0002",
    "slug": "tolsim",
    "dir": "2025_0002_tolsim_melodi",
    "year": 2025,
    "seq": 2,
    "ordinal": 1,
    "title": "TOLSim",
    "subtitle": "Kinetic-joint MR builder",
    "by": [
      "Melodi"
    ],
    "role": "Concept prototype · Unreal Engine XR",
    "place": "Prototype · Turkey",
    "date": "2025",
    "status": "ready",
    "tags": [
      "Mixed Reality",
      "Unreal Engine",
      "Physics",
      "Kinetic Architecture"
    ],
    "links": [],
    "qrTarget": "https://0xg.gg/#tolsim",
    "qr": "/assets/2025_0002/qr.svg",
    "accent": "#4fe37e",
    "media": [
      {
        "kind": "video",
        "src": "/assets/2025_0002/com-oculus-vrshell-20250410-130921-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0002/com-oculus-vrshell-20250410-130921-0.mp4"
          }
        ],
        "poster": "/assets/2025_0002/com-oculus-vrshell-20250410-130921-0.jpg",
        "width": 1024,
        "height": 1024,
        "duration": 189,
        "alt": "Building a joint structure in mixed reality",
        "caption": "Snapping sticks and joints into form, in passthrough MR."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0002/com-oculus-vrshell-20250410-132556-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0002/com-oculus-vrshell-20250410-132556-0.mp4"
          }
        ],
        "poster": "/assets/2025_0002/com-oculus-vrshell-20250410-132556-0.jpg",
        "width": 1024,
        "height": 1024,
        "duration": 117,
        "alt": "Assembling geometric forms from the joint system",
        "caption": "Each piece is a patented joint or stick — combined into geometry."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0002/com-oculus-vrshell-20250410-131550-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0002/com-oculus-vrshell-20250410-131550-0.mp4"
          }
        ],
        "poster": "/assets/2025_0002/com-oculus-vrshell-20250410-131550-0.jpg",
        "width": 1024,
        "height": 1024,
        "duration": 236,
        "alt": "Extended MR building session",
        "caption": "A longer build, testing the system's range of forms."
      }
    ],
    "todos": [
      "Fetch the information from videos, also export a meaningful screenshot image."
    ],
    "body": "**TOLSim** is a small physics + mixed-reality builder prototype, made to\nexperiment with a custom **kinetic joint system** that a kinetic-architect friend\ndesigned and patented. There is one type of joint and one type of stick; from\nthose two primitives you assemble different geometric forms in passthrough MR.\n\nI built it in **Unreal Engine** as an XR app — joints and sticks that snap\ntogether with simulated physics, so the patented system can be felt and tested by\nhand. It was prototyped to support an application for a government grant in Turkey."
  },
  {
    "code": "2025_0003",
    "displayCode": "2025.0003",
    "slug": "altered",
    "dir": "2025_0003_altered_state_000_cyberdelxhack",
    "year": 2025,
    "seq": 3,
    "ordinal": 2,
    "title": "Synesthesia MR",
    "subtitle": "Cyberdelic Hackathon · Berlin",
    "by": [
      "Cyberdelic Nexus Society"
    ],
    "role": "Meta Quest MR app · sensors · GLSL",
    "place": "Berlin",
    "date": "8–9 Nov 2025",
    "status": "ready",
    "tags": [
      "Mixed Reality",
      "Meta Quest",
      "Audio-reactive",
      "Sensors",
      "GLSL"
    ],
    "links": [
      {
        "label": "luma · event",
        "url": "https://luma.com/x66rm5gu",
        "kind": "event"
      },
      {
        "label": "cyberdelic nexus",
        "url": "https://cyberdelicnexus.carrd.co/",
        "kind": "social"
      }
    ],
    "qrTarget": "https://0xg.gg/#altered",
    "qr": "/assets/2025_0003/qr.svg",
    "accent": "#77e65c",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2025_0003/photo-2026-06-28-10-55-14-am.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0003/photo-2026-06-28-10-55-14-am.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0003/photo-2026-06-28-10-55-14-am.webp"
          }
        ],
        "width": 1248,
        "height": 832,
        "placeholder": "data:image/webp;base64,UklGRpIAAABXRUJQVlA4IIYAAAAQBACdASoUAA0APu1iqk2ppaQiMAgBMB2JbAAAXKdbiRNboVPjrhmNAAD+8tgMvevExu2O9BUIfKVlrRgRo/aLi3N87EjKun+9hsiJFM91P6nhJaSIESK4svjiwzE5I8Ej4Cwf8Daq59Wa/7nJJjxQG3///J9/Id39Jubcj67fudF/gAAAAA==",
        "alt": "Cyberdelic Hackathon banner, Berlin, 8–9 Nov 2025",
        "caption": "Cyberdelic Hackathon — Berlin, 8–9 November 2025."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0003/com-oculus-metacam-20251129-205303-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0003/com-oculus-metacam-20251129-205303-0.mp4"
          }
        ],
        "poster": "/assets/2025_0003/com-oculus-metacam-20251129-205303-0.jpg",
        "width": 1280,
        "height": 720,
        "duration": 54,
        "alt": "Vision altered in real time over an industrial venue",
        "caption": "Passthrough vision re-rendered from live sensor data."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0003/img-0074.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0003/img-0074.mp4"
          }
        ],
        "poster": "/assets/2025_0003/img-0074.jpg",
        "width": 720,
        "height": 1280,
        "duration": 33,
        "alt": "The sensor rig — laptop, electronics and a biotron fruit sensor",
        "caption": "Touching fruit drives the visuals — the biotron sensor rig."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0003/com-oculus-metacam-20251203-133539-0.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0003/com-oculus-metacam-20251203-133539-0.mp4"
          }
        ],
        "poster": "/assets/2025_0003/com-oculus-metacam-20251203-133539-0.jpg",
        "width": 1280,
        "height": 720,
        "duration": 49,
        "alt": "Audio-reactive vision alteration",
        "caption": "Microphone input bends the world as you move through it."
      },
      {
        "kind": "image",
        "src": "/assets/2025_0003/photo-2026-06-28-10-55-42-am.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0003/photo-2026-06-28-10-55-42-am.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0003/photo-2026-06-28-10-55-42-am.webp"
          }
        ],
        "width": 1248,
        "height": 832,
        "placeholder": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUAA0APu1iqk2ppaQiMAgBMB2JYwDCgCG8lI01aXfzA9kAAP7yqi1SQ0BvJOFFXfewiJcOnn7rTvpPJJoKZk3jWB57GXVPLXDSBpcCcPuOFHGbhNpPyAAA",
        "alt": "Hackathon, Berlin"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0003/photo-2026-06-28-10-56-01-am.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0003/photo-2026-06-28-10-56-01-am.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0003/photo-2026-06-28-10-56-01-am.webp"
          }
        ],
        "width": 832,
        "height": 1248,
        "placeholder": "data:image/webp;base64,UklGRvwAAABXRUJQVlA4IPAAAAAQBwCdASoUAB4APu1kq0+ppSOiMBgIATAdiWwAtRqDyDXb/4aXAG9I38K0jZ8J+CULCJMw0lzPrjl7oLvfurAdAAD+9o1EWLRgj0qmcqU1GMkGdltTErxEtuZnT9Uzk4zVL7JofAXNcGKYDChVz5mGBjsoT+5osTCEC0skjSWzuE7dxHkYXMCeerqsTzgONvEE6zeIC7a0nEYJEj56Rj6GyiO6M9BisA/QkoE7J5MzwO2gio9//gv1YdjBKtA+tMKz0tGY8X74660Vy4X08enenaGQvNUBZ2VU17N1s5FC0OzyQs+yhMoIMnpMjcd6AAA=",
        "alt": "Hackathon, Berlin"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0003/photo-2026-06-28-10-56-04-am.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0003/photo-2026-06-28-10-56-04-am.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0003/photo-2026-06-28-10-56-04-am.webp"
          }
        ],
        "width": 1248,
        "height": 832,
        "placeholder": "data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAABQBACdASoUAA0APu1iqU2ppaOiMAgBMB2JbACdMoADTrNGCaFDfiwptnoAAP70Kn3pYkLtGT5o5IaJw2db520V1ywbe3TfyZSbgHsrBJaRT0Hjfj7h4fuodPa21UG10Bb7EJgKOl5gAuQtbBfOc5JB8yTO//7UEAA=",
        "alt": "Hackathon, Berlin"
      }
    ],
    "todos": [
      "Fetch the information from event page. save it as md and also assets relative.",
      "Explain the hackhathon then my application.",
      "I'll also add more photos here later on."
    ],
    "body": "For the **Cyberdelic Hackathon** (Berlin, 8–9 Nov 2025), with the **Cyberdelic\nNexus Society**, I built a **Meta Quest** mixed-reality app that alters your\nvision from real-time sensor data.\n\nHere the signal came from a **microphone** (audio-reactive) and from **touching\nfruits and vegetables** (a biotron sensor) — but the idea generalizes to any\nsensor: EEG, pressure, heart rate. I later experimented with touching walls and\nsurfaces to open custom **portals** rendering GLSL shaders I was curating."
  },
  {
    "code": "2025_0004",
    "displayCode": "2025.0004",
    "slug": "nitef",
    "dir": "2025_0004_nitef_joaquina",
    "year": 2025,
    "seq": 4,
    "ordinal": 3,
    "title": "Nostalgia is the Extended Feedback",
    "subtitle": "Solo exhibition · SOMA Art Berlin",
    "by": [
      "Joaquina Salgado"
    ],
    "role": "Trackball + screen · electronics + programming",
    "support": "Trackball and small screen, aided with electronics and programming.",
    "place": "SOMA Art, Berlin",
    "date": "2025",
    "status": "ready",
    "tags": [
      "Installation",
      "Interactive",
      "Electronics"
    ],
    "links": [
      {
        "label": "joaquinasalgado.com/nitef",
        "url": "https://joaquinasalgado.com/nitef",
        "kind": "site"
      }
    ],
    "qrTarget": "https://0xg.gg/#nitef",
    "qr": "/assets/2025_0004/qr.svg",
    "accent": "#a2c267",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2025_0004/img-0119.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/img-0119.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/img-0119.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRtQAAABXRUJQVlA4IMgAAACQBQCdASoUABsAPu1qrVCppaQiqAqpMB2JbACdMoR5j3UBVVw7/yBtQ5VrPUcg0PikXwJZJAD+40sx2UurjJYwX2kUYuKrVQpMa5pewwVwXGRf5R31CcYl7sDROzikEurZPnqLau7b8OxrHe2IgIh8+kI7uMjIj0jH3VZszK9hxP/HxypEcT8GIMdqAa8QsNXhZMSR+5k1IuWQXEcYs5gVxiwLtUPhKR0dUlvFMlX+XqGCETA3KbfQwNarDXVUc8XxHvwsM6wAAA==",
        "alt": "A CRT-like screen in an inflatable sculpture, held with a trackball",
        "caption": "A small screen nested in a glowing inflatable base; a trackball in hand."
      },
      {
        "kind": "video",
        "src": "/assets/2025_0004/img-0117.mp4",
        "sources": [
          {
            "type": "video/mp4",
            "src": "/assets/2025_0004/img-0117.mp4"
          }
        ],
        "poster": "/assets/2025_0004/img-0117.jpg",
        "width": 720,
        "height": 1280,
        "duration": 30,
        "alt": "The installation in the dark gallery",
        "caption": "Aquatic feedback imagery, navigated by trackball."
      },
      {
        "kind": "image",
        "src": "/assets/2025_0004/img-0120.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/img-0120.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/img-0120.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRoAAAABXRUJQVlA4IHQAAABwBACdASoUABsAPu1mq06ppaOiKA1RMB2JQBhQAhyxL85BpAHlQUlJ5B9rQAD+weaZdu0fOxp31b5fiKV15nGtuPI0j9HoRs/yb5iU7fsFyvnG87XeYvasQOCrtA+NrgbgkfCgJzBo31S4XitI42tIAAAAAA==",
        "alt": "Wider view of the installation at SOMA Art Berlin",
        "caption": "Inflated translucent forms and glowing pedestals in the brick hall."
      },
      {
        "kind": "image",
        "src": "/assets/2025_0004/img-0121.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/img-0121.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/img-0121.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAACwAwCdASoUAA8APu1iqk2ppaQiMAgBMB2JQBWAA86dmWL2ZoYVwAD+wFFullAjuySHUMLtggdix//ttWWaWsX8JJoc5Zb9r1om0jsEv3tlEGyypj4FeoWqC/pLGJtFcAINCftos96ZQC0pd3CnsiVQgAA=",
        "alt": "The piece in the SOMA Art space"
      },
      {
        "kind": "image",
        "src": "/assets/2025_0004/img-0122.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2025_0004/img-0122.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2025_0004/img-0122.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRqQAAABXRUJQVlA4IJgAAADwAwCdASoUABsAPu1urlIppiQiqAgBMB2JZgC1F68AqAgfXbhUWVooAP7s/Q0ilUuePsXCpn3q8prJTvZeSpn4Exxz2gTyP/E5lblHnc7zn1lubdR3y/kljbuLF1T2sURQKuQW5/gfwdkVCw0NSa5SDC0D4suH3Mbx76e0OBdd7CsY15N7iInRTQ+pHAPv8uDoefdn5LesAA==",
        "alt": "The piece in the SOMA Art space"
      }
    ],
    "todos": [
      "Fetch the information from website: https://joaquinasalgado.com/nitef. save it as md and also assets relative.",
      "Explain the project, that solo exhibition (SOMA Art Berlin) and my involvement",
      "I'll also add more photos here later on."
    ],
    "body": "*Nostalgia is the Extended Feedback* is a solo exhibition by **Joaquina Salgado**\nat **SOMA Art, Berlin** — a dim brick hall of inflatable forms, glowing pedestals\nand a small screen showing aquatic feedback imagery you steer by hand.\n\nMy support was the interactive layer: a **trackball and small screen**, aided with\n**electronics and programming**, so visitors could move through the feedback\nworld of the piece."
  },
  {
    "code": "2026_0001",
    "displayCode": "2026.0001",
    "slug": "research",
    "dir": "2026_0001_research_jam_chaos",
    "year": 2026,
    "seq": 1,
    "ordinal": 4,
    "title": "Chaos Jam & Research",
    "subtitle": "Collective Chaos Emblematic e.V.",
    "by": [
      "Collective Chaos Emblematic e.V."
    ],
    "role": "Live visuals · custom tools · research",
    "place": "Berlin",
    "date": "2026 — ongoing",
    "status": "ready",
    "tags": [
      "Live Visuals",
      "Performance",
      "Spatial Computing",
      "Research"
    ],
    "links": [
      {
        "url": "https://www.instagram.com/p/DY5RrX9irhg",
        "label": "instagram.com",
        "kind": "social"
      },
      {
        "url": "https://www.instagram.com/p/DVdold8CrQw/",
        "label": "instagram.com",
        "kind": "social"
      }
    ],
    "qrTarget": "https://0xg.gg/#research",
    "qr": "/assets/2026_0001/qr.svg",
    "accent": "#d1779e",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2026_0001/img-0516.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0001/img-0516.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0001/img-0516.webp"
          }
        ],
        "width": 2000,
        "height": 1500,
        "placeholder": "data:image/webp;base64,UklGRqIAAABXRUJQVlA4IJYAAABQBACdASoUAA8APu1iqU2ppaQiMAgBMB2JbACdH8GJtgKVNuf/8PfS+qAQAP3vLsz535T03gTLjJmp+x76Nf3Qts2o5Lr9rRKuuAbXQc170b4OieSQknhodLpR+mTyvsLFnDqdwsBdrgLWYCSui8QyPkAeOKnIGPkPH2nEZPddnIJV7qmZinqlstvI24pEgxb8C4aAAAA=",
        "alt": "Performers before a large psychedelic-glitch projection at a jam",
        "caption": "Live visuals at a Chaos jam — movement meeting the projection."
      }
    ],
    "todos": [
      "Fetch the information from relevant pages. chaos emblematic side has the general info",
      "Download images and videos from instagram posts: https://www.instagram.com/p/DY5RrX9irhg, and https://www.instagram.com/p/DVdold8CrQw/ timestamp them mark/prefix them with YYYYMMDDDD_ig_<instagram_id>_... Keep the reference of the post somewhere, we'll show that as alt later.",
      "Explain the collective, jam and research formats very shortly (1-2 sentences) and my involment and participation.",
      "I'll also add more photos and media here later on."
    ],
    "body": "With **Collective Chaos Emblematic e.V.** I join jams regularly to perform visuals\nand bring custom-made tools, devices and scenes to experiment with — and, more\nrecently, to research.\n\nI'm drawn to **spatial computing** and the live feedback loop between\n**movement ⟷ sound ⟷ visuals**, working across disciplines with others in the\ncollective. *(More media — including documentation from recent jams — to follow.)*"
  },
  {
    "code": "2026_0002",
    "displayCode": "2026.0002",
    "slug": "0xgcg",
    "dir": "2026_0002_0xgcg_nodeinst",
    "year": 2026,
    "seq": 2,
    "ordinal": 5,
    "title": "0xGCG — Grow. Corrupt. Glitch.",
    "subtitle": "Immersive room · Kunstkraftwerk Leipzig",
    "by": [
      "0xG"
    ],
    "role": "Concept · Three.js · immersive direction",
    "place": "Kunstkraftwerk, Leipzig",
    "date": "2026",
    "status": "ready",
    "featured": true,
    "tags": [
      "Immersive",
      "Three.js",
      "Generative",
      "Projection"
    ],
    "links": [
      {
        "label": "0xgcg.0xg.gg",
        "url": "https://0xgcg.0xg.gg",
        "kind": "site"
      },
      {
        "label": "Node Institute · masterclass",
        "url": "https://thenodeinstitute.org/courses/creative-masterclass-immersive-room/",
        "kind": "site"
      },
      {
        "url": "https://thenodeinstitute.org/courses/foundations-immersive-room/?v=5f02f0889301",
        "label": "thenodeinstitute.org",
        "kind": "site"
      }
    ],
    "qrTarget": "https://0xg.gg/#0xgcg",
    "qr": "/assets/2026_0002/qr.svg",
    "accent": "#ff2bd6",
    "media": [
      {
        "kind": "image",
        "src": "/assets/2026_0002/0xgcg-1-intro.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0002/0xgcg-1-intro.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0002/0xgcg-1-intro.webp"
          }
        ],
        "width": 1600,
        "height": 900,
        "placeholder": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAACwAgCdASoUAAsAPu1iqk2ppaQiMAgBMB2JaQAAeyAA/vDuK+9B6MpzfwrAAA==",
        "alt": "0xGCG title — Grow. Corrupt. Glitch.",
        "caption": "The seed: a matrix rain resolves into the title."
      },
      {
        "kind": "image",
        "src": "/assets/2026_0002/0xgcg-2-boot.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0002/0xgcg-2-boot.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0002/0xgcg-2-boot.webp"
          }
        ],
        "width": 1600,
        "height": 900,
        "placeholder": "data:image/webp;base64,UklGRlgAAABXRUJQVlA4IEwAAACQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JaQAAOQKQ4nN5c0qAAP7ytUm7Ysgg6xofrmmhuWXUGskvkzzAgbDXhqDgD0ZpfjTAAAAA",
        "alt": "INIT — the dark machine idles",
        "caption": "I · INIT — a black attractor with gravity, awaiting input."
      },
      {
        "kind": "image",
        "src": "/assets/2026_0002/0xgcg-3-grow.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0002/0xgcg-3-grow.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0002/0xgcg-3-grow.webp"
          }
        ],
        "width": 1600,
        "height": 900,
        "placeholder": "data:image/webp;base64,UklGRl4AAABXRUJQVlA4IFIAAACwAwCdASoUAAsAPu1iqU2ppaQiMAgBMB2JaQAAVMCocDVINJZR8AD+8uJgHgSOGuv27SBqv9GKxymYCyWe0d3ViZgefJJZBPegBRErqIkgAAAA",
        "alt": "GROW — the signal becomes alive",
        "caption": "II · GROW — particles snap into cells, roots and mycelium."
      },
      {
        "kind": "image",
        "src": "/assets/2026_0002/0xgcg-4-corrupt.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0002/0xgcg-4-corrupt.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0002/0xgcg-4-corrupt.webp"
          }
        ],
        "width": 1600,
        "height": 900,
        "placeholder": "data:image/webp;base64,UklGRm4AAABXRUJQVlA4IGIAAACwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JaQAAPfTyksV6xtGGAAD+7ET3cDUArJLRyffSq/tpbae2Oc5xEufn5qS2SZvfMx++0pqgPAYH6LQalhapqusRQ2ix3NieXQAAAA==",
        "alt": "OVERFIT — growth past its substrate",
        "caption": "IV · OVERFIT — replicators and circuitry overrun the field."
      },
      {
        "kind": "image",
        "src": "/assets/2026_0002/0xgcg-5-glitch.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0002/0xgcg-5-glitch.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0002/0xgcg-5-glitch.webp"
          }
        ],
        "width": 1600,
        "height": 900,
        "placeholder": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADwAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JaQAAW+AUYPYoi6I+vSdAAP7xGTz3fa51SB1xLHKZYQGi3C1IXDb/TPYW3z7vHXK8BL7HDvzw3j8cusDvehq9VLbaViUaIGQ0AyAAAAA=",
        "alt": "GLITCH — collapse and return to seed",
        "caption": "V · GLITCH — recognition, datamosh, the loop returns."
      },
      {
        "kind": "image",
        "src": "/assets/2026_0002/0xgcg-6-layout.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0002/0xgcg-6-layout.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0002/0xgcg-6-layout.webp"
          }
        ],
        "width": 1600,
        "height": 900,
        "placeholder": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAABQAwCdASoUAAsAPu1iqU2ppaOiMAgBMB2JaQAAetHPa7kUgAD+8LdN7OLgfnrlV/uqxCOA4FBfKDTe63MTjgAA",
        "alt": "The venue blueprint — Maschinenhalle, Kunstkraftwerk",
        "caption": "Mapped onto the Maschinenhalle's surfaces."
      },
      {
        "kind": "image",
        "src": "/assets/2026_0002/0xgcg-7-timeline.webp",
        "sources": [
          {
            "type": "image/avif",
            "src": "/assets/2026_0002/0xgcg-7-timeline.avif"
          },
          {
            "type": "image/webp",
            "src": "/assets/2026_0002/0xgcg-7-timeline.webp"
          }
        ],
        "width": 1500,
        "height": 950,
        "placeholder": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAACQAwCdASoUAA0APu1iqU2ppaOiMAgBMB2JaQAAVEUEuazHp6FgAP7yuYcK/K9kd5XpSQm0kr3gRRxTtF+6z11RVqPtvRRaQpzkXS1Ju0/ppR9FSad2tcBS7b9keXm+VrYSH1AAAAA=",
        "alt": "The neuron-graph storyboard",
        "caption": "The 5-act dramaturgy as a navigable neuron graph."
      }
    ],
    "todos": [
      "Fetch the information from course pages and about the place too from Kunstkraftwerk's website.",
      "Get also the information about the project etc from the directory mentioned above. at the end of the day, it'll be hosted at 0xgcg.0xg.gg.",
      "I'll also add more information later on. project directory may also include interested videos."
    ],
    "body": "**0xGCG — Grow. Corrupt. Glitch.** is a three-minute immersive video loop for the\nprojection hall at **Kunstkraftwerk, Leipzig**, developed through the **Node\nInstitute** *Creative Masterclass: Immersive Room*.\n\nIt is a helical meta-narrative of systems — how they emerge, **grow**, **optimize**,\n**overfit**, and finally **glitch** into the seed of another dimension, then loop.\nAmid the AI boom and its daily dread-and-excitement, I'm co-creating it with my\ndigital twin, **0xG** (a Claude Code instance), as an open discussion that goes\nmeta and questions the question itself — not from a protagonist's view but as the\nwhole system's.\n\nThe concept began as a Three.js explorer, deployed separately at\n**[0xgcg.0xg.gg](https://0xgcg.0xg.gg)** — scan or follow the link to fly through it."
  }
]
